#!/usr/bin/env ruby

require 'yaml'
require 'dbus'

$ignore = %w[
  /xfce4-keyboard-shortcuts/commands/default
  /xfce4-keyboard-shortcuts/commands/custom/override
  /xfce4-keyboard-shortcuts/xfwm4/default
  /xfce4-keyboard-shortcuts/xfwm4/custom/override
  /xfce4-keyboard-shortcuts/providers
  /xfce4-session/sessions/Failsafe
  /xfce4-desktop/backdrop
  /xfce4-appfinder/actions
  /xfce4-notifyd/applications/known_applications
  /displays
  /xfce4-desktop/last
  /xfce4-appfinder/last
  /xfce4-settings-manager/last
  /xfce4-settings-editor/last
  /xfce4-mime-settings/last
  /thunar/last
]

$xfconf = DBus.session_bus['org.xfce.Xfconf']['/org/xfce/Xfconf']['org.xfce.Xfconf']
$defaults = YAML.load(File.read('defaults.yml'))

$settings = {}
$shortcuts = { 'commands' => {}, 'wm' => {} }

channels = $xfconf.ListChannels()

channels.each do |channel|
  props = $xfconf.GetAllProperties(channel, '/')
  if channel == 'xfce4-keyboard-shortcuts'
    defaults = $defaults['shortcuts']
    props.each do |k, v|
      case k
      when %r{^/commands/custom/(.+)}
        next if $1 == 'override'
        next if defaults['commands'][$1] == v
        $shortcuts['commands'][$1] = v
      when %r{^/xfwm4/custom/(.+)}
        next if $1 == 'override'
        t = v.slice(..-5)
        next if defaults['wm'][t] == $1
        $shortcuts['wm'][t] = $1
      end
    end
    next
  end
  defaults = $defaults['settings'][channel]
  props.reject! { |k, v| defaults[k] == v } if defaults
  props.reject! { |k, v| ('/' + channel + k).start_with?(*$ignore) }
  next if props.empty?
  $settings[channel] = props.sort.to_h
end

puts YAML.dump({ 'shortcuts' => $shortcuts, 'settings' => $settings })
