shortcuts:
  commands:
    "<Super>Return": xfce4-terminal
    "<Super>b": chromium
  wm:
    left_workspace: "<Super>Left"
    right_workspace: "<Super>Right"
    up_workspace: "<Super>Up"
    down_workspace: "<Super>Down"

settings:
  xfwm4:
    "/general/easy_click": "Super"
    "/general/cycle_tabwin_mode": 1
  xfce4-session:
    "/general/SaveOnExit": false
  xfce4-desktop:
    "/desktop-icons/style": 0
